27 post history
freebites/product pull request #34
Opened 2024-06-06 18:00 UTC by Jet4stream

# Description

1. Created the functionality and the frontend work for the delete icon, including the modal that pops up when the trash icon is pressed.
2. Corrected the functionality of the "Your Post" to only show the posts that you post yourself.
3. Created the functionality of the "Post History" to show the posts that you post yourself.

## Issues

Resolve #27 

## Screenshots

 
<img src="https://github.com/freebites/product/assets/158139019/3b14c69f-77e8-4a0c-ae4d-37109a396c6e" width="200" />
<img src="https://github.com/freebites/product/assets/158139019/4577c663-e38a-461a-919f-0097e5c65c4e" width="200" />
<img src="https://github.com/freebites/product/assets/158139019/d8c6a487-7c67-4e7c-b158-555274deb9ea" width="200" />
<img src="https://github.com/freebites/product/assets/158139019/90fa38e8-ab9b-4fc6-999f-3331df560a20" width="200" />

## Test

1. Create a new post
2. Check "Your Post" to see if the post shows up
3. Check "History" to see if the post shows up
4. Check the post to see if the trash icon is on the post
5. Click on the trash icon to see if the delete modal shows up
6. Hit "Yes" on the delete modal and see if the post automatically deletes from the page
7. Check both "Your Post" and "History" to see if it is deleted there

## Possible Downsides

1. If you delete the post in "History", it still does not disappear from the Home, which could cause some errors if a user does try to open up the post after it's been deleted. However, refreshing the page does fix the problem.
2. The delete modal backdrop when it is open does prevent the user from clicking on other posts, but it doesn't make the modal disappear. 
3. We implemented two new props into the "HomePost" document: setRefreshing and fetchData. This could cause some complications in the future if someone does want to use "HomePost".

## Additional Documentations

 N/A

2024-06-07 00:55 UTC, johnny-t06 requested changes
Good job team on your first PR! The implementation and the modal looks amazing, thanks for the hard work. 
I left a few comments/nits for some code housekeeping things. Also, take a look at the Modal prop OnBackdropPress to handle closing the modal. This is also used in the CommentsModal.

2024-06-07 00:55 UTC, johnny-t06 commented on src/app/(tabs)/home/index.tsx
> +            console.log(userToFilter);
Try to remove console.logs from your code

2024-06-07 00:55 UTC, johnny-t06 commented on src/app/(tabs)/home/index.tsx
> +          // here?
nit: Remove if not needed

2024-06-07 00:55 UTC, johnny-t06 commented on src/app/(tabs)/home/index.tsx
> +              //<Text>{JSON.stringify(eachPost)}</Text>
nit: Remove if not needed

2024-06-07 00:55 UTC, johnny-t06 commented on src/app/(tabs)/post/reviewpost.tsx
> +      });
Here as well!

2024-06-07 00:55 UTC, johnny-t06 commented on src/app/(tabs)/profile/history.tsx
> +  const [refreshing, setRefreshing] = useState(true);
Try to type your states like line 18.
Also, the refreshing should default to false as we aren't refreshing when the History page renders.

2024-06-07 00:55 UTC, johnny-t06 commented on src/app/(tabs)/profile/history.tsx
> +    postData = await getAllPosts();
General convention to use const so the fetched data is not mutated

2024-06-07 00:55 UTC, johnny-t06 commented on src/components/home/DeleteModal.tsx
> +// import { router } from "expo-router";
nit: Remove if not needed

2024-06-07 00:55 UTC, johnny-t06 commented on src/components/home/DeleteModal.tsx
> +            // }}
nit: Remove if not needed

2024-06-07 00:55 UTC, johnny-t06 commented on src/components/home/DeleteModal.tsx
> +                    // router.push("/home");
nit: Remove if not needed

2024-06-07 00:55 UTC, johnny-t06 commented on src/components/home/HomePost.tsx
> +          {/* <Text style={styles.text}>{post._id}</Text> */}
This wasn't your code earlier, but we should probably just display the title here.

2024-06-07 00:55 UTC, johnny-t06 commented on src/components/home/HomePost.tsx
> +        userPost={post.postedBy == user.uid}
nit: Equality checks in Javascript should be done with "===" for strict equality against types as well.

2024-06-07 02:47 UTC, LordofMankid requested changes
rly good stuff! looks like you guys have learned a lot. just a few things to add and change, but overall good work! And thanks for mentioning the refreshing stuff(syncing history and home)! The best fix will most likely be app-level state management which is outside the scope of this ticket, so don't worry about it too much.

2024-06-07 02:47 UTC, LordofMankid commented on src/components/home/DeleteModal.tsx
> +              <View style={styles.cancelButton}>
just talked to designers, looks like we don't need this button since 'no' and 'cancel' are the same thing, so you can get rid of this. May need to adjust spacing; check Figma just to be sure!

2024-06-07 02:47 UTC, LordofMankid commented on src/app/(tabs)/profile/history.tsx
> +            No history yet
might've been me who originally wrote this LOL but can you move inline styles for text down to StyleSheet? also small nitpick, put it in container that's slightly less wide - check figma (i'd say 65% screen width to eyeball)

2024-06-07 02:47 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
>          {AllPosts.map((eachPost: postType) => {
Small addon but since you added it to History.tsx already -- can you add the "no history yet" if there's no posts in "Your Posts?" You can use a ternary operator similar to the one in History, where our condition is AllPosts.length === 0 && UserToFilter !== ""

true case is "no history", and false case is original AllPosts.map stuff

2024-06-11 01:22 UTC, LordofMankid approved these changes
LGTM, pending johnny review

2024-06-11 02:28 UTC, johnny-t06 approved these changes
LGTM, made a few changes to the modal backdrop and conditional rendering on the Home index. Feel free to merge your changes into main!

2024-06-12 19:07 UTC, merged