Async Storage & App State #31
freebites/product pull request #40
Opened 2024-06-09 15:07 UTC by ManuP6789

# Description

We implemented the functionality for users to save settings, app state, and other necessary data using Async Storage.
We used this functionality to store locally:

- Notification options
- User location
- Post Dietary filters

## Issues

Resolve #31 

## Screenshots

![IMG_1521](https://github.com/freebites/product/assets/143857167/c5590a47-c0f6-483d-b224-bcc3effa9827)
![IMG_1522](https://github.com/freebites/product/assets/143857167/0e60a3b9-f450-446c-9c32-e5225b408b25)

## Test

Test Location:

1. Open app on Expo
2. Go to Home page
3. Click search bar
4. Type in a location of your choice (you should see the console log "updating location:...")
5. Reload the app
6. Click search bar in home page
7. Look at console log and it should display the same location

Test Filters:

1. Open app on Expo
2. Go to Home page
3. Click sidebar icon on the top right
4. Click any filters of your choice (you should see the console log displaying filters chosen)
5. Reload the app
6. Click sidebar icon on the top right
7. Look at console log and it should display the filters you choose before

Test Notifications:

1. Open app on Expo
2. Go to Profile page
3. Go to settings
4. You should see two filters already toggled on which are the first and third
5. Turn on and off as you wish but make sure you change it differently from default
6. Reload the app
7. You should see the changes you made saved
8. You can also go to home page and back and the settings should still persist

## Possible Downsides

Can only store JSON strings.
Added the local storage functionality for sort but sorting functionality is not fully implemented yet.
Only added functionality for notifications in Settings because everything else is not implemented yet.

## Additional Documentations

We used this documentation:
https://react-native-async-storage.github.io/async-storage/docs/api

2024-06-11 02:39 UTC, LordofMankid requested changes
Everything looks clean. Just check the comments on typing getItem and clean up the console log statements. Great job boys

2024-06-11 02:39 UTC, LordofMankid commented on src/context/appContext.tsx
> +    const getState = async () => {
instead of 4 awaits, we can leverage the power of async functions by wrapping this in a Promise.all -- this would allow all of these state updates to happen concurrently, which will make it faster especially in the long run once we start adding more. 

however, we are using typescript, so make sure all the promises passed in are typed! look at my comment in async storage for how to do that

you'll have to look it up but the syntax is something like const [val1, val2] = await Promise.all([promise1, promise2])

2024-06-11 02:39 UTC, LordofMankid commented on src/local-storage/asyncStorage.ts
> +export const getItem = async (key: string): Promise<any | null> => {
getItem definitely should be polymorphic, but <any> will remove the TypeScript type-checking, and since we have multiple different types, it'll get hard to debug. Instead, support polymorphism through using <T>, or a 'generic type.' [You can read more about it here.](https://www.typescriptlang.org/docs/handbook/2/generics.html)

This will allow you to assign types to getItem like you do in useState, like getItem<string>.

Using <T> or <Type> should look something like this:
export const getItem = async <T>(key: string): Promise<T | null> (just ask chatgpt lmao it's a few line fix)

After that, go through and type all your instances of getItem. If there's a <T | null> you can use a ternary operator or if else statements to guarantee that it's not null:

if (val1) setState(val1) [where setState is expecting <type1> instead of <type1 | null>

2024-06-11 02:39 UTC, LordofMankid commented on src/components/settings/ToggleOption.tsx
> +const ToggleOption = (props: { storageKey: string; text: string }) => {
add interface for this - ToggleOptionProps

2024-06-11 02:39 UTC, LordofMankid commented on src/components/login/SignupSection.tsx
> +      console.log("error here notifsect");
Try to remove console statements like these after you're done. If you do leave some to help reviewers debug, just let us know where in the PR so we can easily remove them once we push!

2024-06-11 03:14 UTC, johnny-t06 requested changes
Great job team on working this one out. I am echoing Clarence's comments and once they're addressed, feel free to re-request us!

2024-06-11 03:14 UTC, johnny-t06 commented on src/components/settings/ToggleOption.tsx
> +const ToggleOption = (props: { storageKey: string; text: string }) => {
+1 on this, then you can de-structure the props as well.

2024-06-11 03:14 UTC, johnny-t06 commented on src/local-storage/asyncStorage.ts
> +export const getItem = async (key: string): Promise<any | null> => {
+1 I'm in favour of typing and constructing return values of this function

2024-06-13 03:32 UTC, johnny-t06 approved these changes
LGTM, good job team. The getItem works well to return a specified type, however we may encounter a null return. So I added a new function called getItemWithDefault which takes in a default value so we get the default value instead of a null return. I think it makes the code a little cleaner than checking all the different values are null. 

Feel free to merge after resolving the merge conflicts!

2024-06-14 01:37 UTC, LordofMankid approved these changes
LGTM

2024-06-23 15:42 UTC, merged