28 profile functionality
freebites/product pull request #42
Opened 2024-06-13 05:44 UTC by Gaelvego

# Description
Implemented users being able to change their profile attributes (firstname, lastname, username, pronouns) and also users being able to change and delete their profile pictures.

## Issues
Resolve #28 

## Screenshots
<img width="289" alt="image" src="https://github.com/freebites/product/assets/108428546/e062ae7a-1c27-43fd-b3c9-5c6db4abf34f">
<img width="296" alt="image" src="https://github.com/freebites/product/assets/108428546/af66a66c-5f6e-4bcd-9b1f-854f7170a620">

## Test
Modify profile attributes

## Possible Downsides
Maybe managing user data across the profiles components would me more effective using context.
Users have a set amount of pronouns to choose from.
Users can not preview the photo that will be set as their profile when they use the take photo option.
The main profile page doesn't update immediately to render new profile changes.

The userName attribute is added to most parts of the repo where it could be relevant, but the database schema was never modified. In theory once the attribute is added to the schema the code should work as is. Pushing a user with new attributes does not give that user new the new attributes, maybe the schema is strict.
Created a new directory on firebase for profile pictures, and used the existing profile attribute on the user schema for the profile pictures. When a user updates their profile picture, the old one is deleted from the database.

## Additional Documentations
Added the react native picker picker select dependency as there are no native pickers.

2024-06-16 14:56 UTC, johnny-t06 commented on src/app/profile/edit.tsx
> +
Small nit: we can use ternary operators to make the code more concise
```
return text ? null : "Pronouns are required"
```
```
return text === "null" ? "Pronouns are required" :  null
```

2024-06-16 14:56 UTC, johnny-t06 commented on src/app/profile/edit.tsx
> +    }
nit: Remove console.logs if not needed

2024-06-16 14:57 UTC, johnny-t06 commented on src/app/profile/edit.tsx
> +
nit: Remove console.logs if not needed

2024-06-16 14:58 UTC, LordofMankid requested changes

2024-06-16 14:59 UTC, johnny-t06 commented on src/components/common/cards/ProfileCard.tsx
> +        const data = await getOneUser(user.uid);
nit: Remove console.logs if not needed

2024-06-16 15:03 UTC, LordofMankid commented on src/app/(tabs)/post/index.tsx
> +      <Camera style={styles.camera} type={type} ref={cameraRef}>
try making this camera screen into its own component. Then you can call this camera component here as well as in the edit modal. then you don't need to pass in 'profile' into local search params, just as a single prop! I'll comment on repeat code you can take out as a result of this change

2024-06-16 15:07 UTC, LordofMankid commented on src/components/profile/EditModal.tsx
> +  const uploadPicture = async (uri: string) => {
repeat logic you can add into the camera component mentioned in home/index, you can clean this up later

2024-06-16 15:07 UTC, LordofMankid commented on src/app/(tabs)/post/index.tsx
> +import EditProfileHeader from "components/profile/EditProfileHeader";
nit: try removing unnecessary imports/code after you're done testing/using it to avoid clutter

2024-06-16 15:09 UTC, johnny-t06 commented on src/app/(tabs)/post/index.tsx
> +      <Camera style={styles.camera} type={type} ref={cameraRef}>
+1 on this

2024-06-16 15:39 UTC, johnny-t06 requested changes
Good job team! Take a look at our comments mainly about the camera refactoring into a component and removing un-needed code. Feel free to re-request us when you guys make changes!

2024-06-30 16:26 UTC, johnny-t06 approved these changes
LGTM, great work team! Looks good to merge on my end

2024-07-01 03:15 UTC, LordofMankid approved these changes
LGTM! put in a comment for a tiny nitpick on prop convention that you can read but no need to change for now. good work guys! looks a lot cleaner, thanks for putting the work for this

2024-07-01 03:18 UTC, LordofMankid commented on src/components/common/Camera.tsx
> +export default function OpenCamera({profile} : OpenCameraProps) {
like the energy for saving a line of code here, but in this case we'd destructure the prop like 
OpenCamera( props: OpenCameraProps) {
const { profile } = props; 
...

just to keep it consistent with how it's used in other places with multiple props. if u want to change before you merge, feel free to but not necessary until the future if we need to add more props.

2024-07-02 06:28 UTC, merged