50 delete during post creation (merge with 47)
freebites/product pull request #57
Opened 2024-07-23 20:26 UTC by owennjpr

# Description

We revamped the modal popup in the post creation window, and added the functionality to the delete button in this modal. We also updated the structure of the modals throughout the app to be more modular and efficient.

## Issues

Resolve #50 

## Screenshots

<img src="https://github.com/user-attachments/assets/3668ea3f-a22d-423e-8463-adaa7dc8863b" width=200 />
<img src="https://github.com/user-attachments/assets/07e27298-af1f-4cd7-af40-a5d8df9404cf" width=200 />

## Test
- log in
- click on the create new post button on the home screen
- take a picture to use for the post
- Continue into the post creation page, however many screens you want to move through
- click the three dots in the top right of the screen, the modal should appear
- press the background or cancel button to close the modal
- press the dots to reopen it
- press the delete button and you should be returned to the home screen with no new post created.

## Possible Downsides

There may still be some references in the code still to the previous implementation of this modal that we missed or failed to remove. Creating new modals will require the use of the FreeBitesModal component from now on as opposed to the react native Modal component. 

## Additional Documentations

2024-07-26 03:05 UTC, johnny-t06 requested changes
Good work so far team, I have a few changes requested. Let us know if anything sounds confusing

2024-07-26 03:05 UTC, johnny-t06 commented on src/components/home/FreeBitesConfirmationModal.tsx
<img src="https://github.com/user-attachments/assets/f18d480d-13b2-4497-836c-5eb871830bb9" width="50%">

Looks a little different from the Figma

2024-07-26 03:05 UTC, johnny-t06 commented on src/components/home/FreeBitesModal.tsx
<img src="https://github.com/user-attachments/assets/520dc48c-97ea-4e03-a36f-4917a49efce9" width="50%">

Can we look to align the text on the left (the Cancel should line up as well) and the icons on the right?

2024-07-28 23:32 UTC, Jet4stream commented
2 things to mention.
- There is a lag between the delete modal and the confirmation delete modal because we need to wait for one modal to close before we open another modal. For this example, we have to wait around 300 milliseconds for the first modal to close.
- The post does not delete when the user presses "yes". Instead, the post is deleted after the user confirms with the confirmation modal. This is because if we delete the post before the confirmation modal, the confirmation modal does not have a chance to show up.

2024-07-30 03:08 UTC, merged