67 admin view
freebites/product pull request #73
Opened 2024-08-25 15:03 UTC by Jet4stream

# Description

We were able to both create the schema and backend functionality to store reports and were able to create the admin view to view all the reports.

## Issues

Resolve #67

## Screenshots

<img src="https://github.com/user-attachments/assets/fc951fa0-788a-49b6-ba25-37a73f5d58d4" width=200>
<img src="https://github.com/user-attachments/assets/2ac9275c-0c2e-4bfd-b5c9-d35ef702a3b3" width=200>
<img src="https://github.com/user-attachments/assets/a1e721b5-4d8f-449e-ac4d-950d0431662b" width=200>
<img src="https://github.com/user-attachments/assets/ab592174-411a-424c-b2ae-86ac1192aa84" width=200>
<img src="https://github.com/user-attachments/assets/4e433e1c-529b-494b-aeec-933827f8fceb" width=200>
<img src="https://github.com/user-attachments/assets/4bbc8630-2122-4588-9e99-a920619f830a" width=200>

## Test

Admin View:
- Log into an account that has admin access (the account we created was owen@mail.com with the same password as test@test.com)
- There should be an "All posts" tab and a "Report" tab
- Under each post under the "All posts" tab, there should be an "Achive" button that deletes the post and a report button that adds a report to the post
- Try reporting a post and see if the report shows up when clicking the "Report" tab.
- Under the "Report" tab, there should be a list of dropdowns that list all the usernames of the people who reported.
- Admin users can press on each report to see the report message and post that is associated with each report.
- The admin user can either ignore the report, archive the post, or add other reports to it

Currently, the only way turning an account into an admin account is if you manually go into the MongoDB Atlas and change their "isAdmin" field to "true".

2024-09-02 06:20 UTC, LordofMankid reviewed
not done yet, the frontend code and API code looks good for the most part, a few things that can be done more efficiently. will finish tomorrow

2024-09-02 06:20 UTC, LordofMankid commented on src/components/home/ReportDropdown.tsx
> +  const {
i like the idea of the useEffect only firing when it's visible, though I'd add a way for it to only fire once after toggling the visibility. 

since admins would want to toggle all reports manually anyway, it may be a good idea to fetch all the info at once so the toggle runs faster. if this is the case, then I'd use Promise.all to fetch all the data in Home simultaneously into an array or arrays of userData/postData/etc, then map through them, passing in the raw data here (userData, postData, etc) without needing fetch in this component. @johnny-t06 what do you think

2024-09-02 06:20 UTC, LordofMankid commented on backend/controllers/reportControllers.ts
> +    reportsToDelete.map(async (report) => {
promise.all the deletes to delete simultaneously

2024-09-02 06:20 UTC, LordofMankid commented on backend/routes/reportRoutes.ts
> +reportRouter.get("/api/Reports", report.getAllReports);
i know this keeps the syntax cleaner, but just for consistency go with the import {getAllReport } ... syntax

2024-09-02 19:55 UTC, LordofMankid requested changes
looks really good! good work guys. caught a few crashing edge cases and added some comments on handling them. added in some comments to refactor to make things easier to read, but please let me know if you want to call (or meet up now :)) to go through things as maybe it's not as clear

2024-09-02 19:55 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
was the admin mode 'toggle' implemented? in the figma there's an option to turn on/off admin mode if you're logged in as an admin and i don't see it rn

2024-09-02 19:55 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
> +      {!viewReported ? (
let me know if i'm wrong, but it looks like you can "unfactor" the viewReported logic here and get rid of this viewReported ternary "wrapper" thing and move the logic onto the component level - it makes sense to do it this way intuitively, but adds a lot of repeated code/structure since not much actually changes. I'll comment more on specifics down below

2024-09-02 19:55 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
> +                AllPosts.map((eachPost) => {
and add viewReported here for to see which array you want to map on

2024-09-02 19:55 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
> +          {userToFilter !== "" &&
can you pull this out into a useMemo that returns a boolean like const noPosts = (() => { userToFilter !== "" && ...} )? would be more readable, then add the viewReported and have this handle both empty states

2024-09-02 19:55 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
> +              title={"No history yet"}
then here you can have a ternary operator to select which text to use

2024-09-02 19:55 UTC, LordofMankid commented on src/components/home/ArchiveModal.tsx
> +  const deleteFunc = async () => {
can you just turn this into a useCallback? want to pivot to using these just to be more consistent (their behavior is more consistent as well)

2024-09-03 02:29 UTC, johnny-t06 requested changes
Great work guys, Clarence left some great comments + I have some as well. 

Also lets fix the scrolling when multiple dropdowns are on
https://github.com/user-attachments/assets/49083226-a005-4b51-9397-c086c352c573

2024-09-03 02:29 UTC, johnny-t06 commented on src/components/home/OptionModel.tsx
> +      postID: singlePost._id ? singlePost._id : "",
you can do a use a nullary coalesing operator here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2024-09-03 02:29 UTC, johnny-t06 commented on src/components/home/OptionModel.tsx
>    };
remove logs

2024-09-03 02:29 UTC, johnny-t06 commented on src/components/home/ReportDropdown.tsx
> +  const {
Good catch, yeah I do think fetching on toggle is not the best idea. However if we bring the fetching outside of this component into Home index, this would slow down loading times yet again. (Well I guess for admins, still something we should consider). Probably best way would to fetch once of all reports when an admin clicks on the reported tab

2024-09-03 02:29 UTC, johnny-t06 commented on src/components/home/ArchiveModal.tsx
> +        headText="You successfully archived your post!"
*archived this or the*

2024-09-03 19:43 UTC, Jet4stream commented on src/app/(tabs)/home/index.tsx
> +  const [AllReports, setReports] = useState<ReportType[]>([]);
Although we don't have a null case, the reports associated with the deleted post should be deleted as well with our "deleteByPost" API. We will still add a null case just in case the app glitches, but just wanted to let you know that all reports associated with a deleted report should be deleted as well.

2024-09-03 19:49 UTC, LordofMankid commented on src/app/(tabs)/home/index.tsx
> +  const [AllReports, setReports] = useState<ReportType[]>([]);
oh yeah just to clarify it's on posts that aren't deleted properly (aka when we wiped the posts off the database)

2024-09-03 19:51 UTC, owennjpr commented on tsconfig.json
we don't think we added it. if we did it was not intended

2024-09-03 19:57 UTC, LordofMankid commented on tsconfig.json
ok think it was a merge thing dw about it

2024-09-07 15:19 UTC, owennjpr commented on backend/routes/reportRoutes.ts
> +reportRouter.get("/api/Reports", report.getAllReports);
What do you mean exactly by the import {getAllReport} syntax? our syntax seems to match the other routers, unless we are missing something?

2024-09-07 15:24 UTC, LordofMankid commented on backend/routes/reportRoutes.ts
> +reportRouter.get("/api/Reports", report.getAllReports);
import { getAllReports, ... } (import them individually)

reportRouter.get("/api/Reports", getAllReports); instead of import.getAllReports

2024-09-08 15:45 UTC, merged